// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHrKW99Jg-u-nzWZzWCTyia8PmvJqoac',
    appId: '1:219834135889:web:84ba54a54db45936b04f70',
    messagingSenderId: '219834135889',
    projectId: 'mindfulchatproject',
    authDomain: 'mindfulchatproject.firebaseapp.com',
    storageBucket: 'mindfulchatproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGeL_PQpAiiE_XaVGUZESx4KMJ_iErzpo',
    appId: '1:219834135889:android:c244cba7bca3ecabb04f70',
    messagingSenderId: '219834135889',
    projectId: 'mindfulchatproject',
    storageBucket: 'mindfulchatproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynHEgjJoF0UhRBs_XvW6S2CnFHTzvzWI',
    appId: '1:219834135889:ios:a1d26e79fbe06923b04f70',
    messagingSenderId: '219834135889',
    projectId: 'mindfulchatproject',
    storageBucket: 'mindfulchatproject.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBynHEgjJoF0UhRBs_XvW6S2CnFHTzvzWI',
    appId: '1:219834135889:ios:a1d26e79fbe06923b04f70',
    messagingSenderId: '219834135889',
    projectId: 'mindfulchatproject',
    storageBucket: 'mindfulchatproject.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgHrKW99Jg-u-nzWZzWCTyia8PmvJqoac',
    appId: '1:219834135889:web:c81815fc704b2a84b04f70',
    messagingSenderId: '219834135889',
    projectId: 'mindfulchatproject',
    authDomain: 'mindfulchatproject.firebaseapp.com',
    storageBucket: 'mindfulchatproject.firebasestorage.app',
  );
}
